type Customer {
  _id: ID!
  name: String!
  email: String!
  password: String!
  active: Boolean!
  roles: [String!]!
}

input CustomerInput {
  name: String!
  email: String!
  password: String!
  active: Boolean!
  roles: [String!]!
}

type Query {
  customers: [Customer!]!
  customer(id: ID!): Customer!
  customerByEmail(email: String!): Customer!
  customersActive: [Customer!]!
  customersByRoles(role: String!): [Customer!]!
}

type Mutation {
  createCustomer(data: CustomerInput!): Customer!
  updateCustomer(id: ID!, data: CustomerInput!): Customer!
  deleteCustomer(id: ID!): Boolean
}
